Aaron
data-faking/faking pull request #24
Opened 2023-12-10 23:30 UTC by AaronPatterson1

2023-12-11 07:32 UTC, clearfeld requested changes
I'd say for the pantone colors we should split it into 2.

instead of the string being like so "#f4ed7c  Pantone 100 C",

it should either be "#f4ed7c" or "Pantone 100 C".

The array structure is fine but probably make 2 more functions that return either the hex code directly or the name itself.

2023-12-13 09:37 UTC, AaronPatterson1 commented
Added a couple more functions to split the Pantone Color string and return either the hexcode or the name, please review.

2023-12-14 22:22 UTC, clearfeld approved these changes

2023-12-14 22:23 UTC, clearfeld commented
LGTM

2023-12-14 22:23 UTC, merged