Add name() and name_with_middle() fn
data-faking/faking pull request #99
Opened 2024-04-03 08:19 UTC by sibeizhou

And modified some use of the function related

2024-04-03 17:26 UTC, clearfeld requested changes

2024-04-03 17:26 UTC, clearfeld commented on src/locales/en/food/dish_pattern.rs
>  pub fn dish_parttern() -> String {
Typo `parttern` instead of `pattern`

2024-04-03 17:26 UTC, clearfeld commented on src/locales/en/location/city_parttern.rs
>  pub fn city_parttern() -> String {
Typo and in the name of the file

2024-04-03 17:26 UTC, clearfeld commented on src/locales/en/location/street_parttern.rs
>  pub fn street_parttern() -> String {
Same here

2024-04-03 21:02 UTC, sibeizhou commented
Already fixed the typo mistakes

2024-04-04 04:40 UTC, clearfeld approved these changes

2024-04-04 04:40 UTC, merged